# Generated by Django 3.1.12 on 2026-02-17 10:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='', max_length=150, unique=True)),
                ('description', models.TextField(default='')),
                ('logo', models.ImageField(default=None, upload_to='club_logos/')),
                ('entry_fees', models.IntegerField(default=0, help_text='0 means FREE')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'BSC'), ('MSC', 'MSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BALLAB', 'BALLAB'), ('LLB', 'LLB')], default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_fees', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_free', models.BooleanField(default=False)),
                ('event_video', models.FileField(blank=True, null=True, upload_to='event_videos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.club')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('qid', models.CharField(default='000000', max_length=15, unique=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(blank=True, default=True, null=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('FACULTY', 'FACULTY'), ('DEAN', 'DEAN'), ('VC', 'VC'), ('DIRECTOR', 'DIRECTOR'), ('NON-FACULTY', 'NON-FACULTY'), ('ADMIN', 'ADMIN')], default='STUDENT', max_length=100)),
                ('country_code_for_mobile', models.CharField(default='00', max_length=10)),
                ('mobile', models.CharField(default='0000000000', max_length=15)),
                ('program', models.CharField(blank=True, choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'BSC'), ('MSC', 'MSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BALLAB', 'BALLAB'), ('LLB', 'LLB')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, choices=[('B.TECH CSE', 'B.TECH CSE'), ('B.TECH CIVIL', 'B.TECH CIVIL'), ('B.TECH MECHANICAL', 'B.TECH MECHANICAL'), ('B.TECH ELECTRICAL', 'B.TECH ELECTRICAL'), ('M.TECH CSE', 'M.TECH CSE'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'BSC'), ('MSC', 'MSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BALLAB', 'BALLAB'), ('LLB', 'LLB')], max_length=50, null=True)),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=5, null=True)),
                ('current_year', models.CharField(blank=True, max_length=5, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.course')),
                ('faculty_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEventEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('actual_enrolled_time', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
                ('student_enrolled', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrolled_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.course')),
                ('subject', models.ManyToManyField(to='Qapp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('qid', models.CharField(blank=True, default='000000', max_length=15, null=True, unique=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('FACULTY', 'FACULTY'), ('DEAN', 'DEAN'), ('VC', 'VC'), ('DIRECTOR', 'DIRECTOR'), ('NON-FACULTY', 'NON-FACULTY'), ('ADMIN', 'ADMIN')], default=None, max_length=100)),
                ('country_code_for_mobile', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_at', models.DateTimeField(default=None, null=True)),
                ('user_requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='notification_file/')),
                ('notificatio_type', models.CharField(blank=True, choices=[('Marking Attendance', 'Marking Attendance')], default=None, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
                ('push_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_by_notification', to=settings.AUTH_USER_MODEL)),
                ('push_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_to_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_coordinator',
            field=models.ManyToManyField(blank=True, related_name='event_coordinator_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='faculty_assigned',
            field=models.ManyToManyField(blank=True, related_name='faculty_assigned_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('member_position', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICE-PRESIDENT', 'VICE-PRESIDENT'), ('CORE-MEMBER', 'CORE-MEMBER'), ('GENERAL-MEMBER', 'GENERAL-MEMBER')], default='GENERAL-MEMBER', max_length=100)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_payment', to='Qapp.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICE-PRESIDENT', 'VICE-PRESIDENT'), ('CORE-MEMBER', 'CORE-MEMBER'), ('GENERAL-MEMBER', 'GENERAL-MEMBER')], default='GENERAL-MEMBER', max_length=100)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='club_membership', to='Qapp.club')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='club_gallery/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Qapp.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_assigned',
            field=models.ManyToManyField(default=None, related_name='faculty_assigned_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs_as_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pushed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('attendance_marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_marked_by_cordinator', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_token', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('section_name', 'course'), name='unique_section_per_course'),
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together={('user', 'club')},
        ),
    ]
