# Generated by Django 5.1.7 on 2026-02-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmembership',
            name='active',
        ),
    ]
