# Generated by Django 5.1.7 on 2026-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('N_FACULTY', 'N_FACULTY'), ('DEAN', 'DEAN')], default=None, max_length=100, null=True),
        ),
    ]
