# Generated by Django 5.1.7 on 2025-11-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0002_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, choices=[('B.tech CSE', 'B.tech CSE'), ('B.tech Civil', 'B.tech Civil'), ('B.tech AI/ML', 'B.tech AI/ML'), ('B.tech Mechanical', 'B.tech Mechanical'), ('BCA', 'BCA'), ('MCA', 'MCA')], default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('section_name', 'course'), name='unique_section_per_course'),
        ),
    ]
