# Generated by Django 5.1.7 on 2026-02-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0002_event_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='event_title',
        ),
    ]
