# Generated by Django 5.1.7 on 2026-02-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0002_remove_clubmembership_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='faculty_assigned',
            field=models.ManyToManyField(default=None, related_name='faculty_assigned_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs_as_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='club_membership', to='Qapp.club'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubpayment',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_payment', to='Qapp.club'),
        ),
        migrations.AlterField(
            model_name='clubpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together={('user', 'club')},
        ),
    ]
