# Generated by Django 5.1.7 on 2026-02-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0003_rename_event_event_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='event',
        ),
    ]
