# Generated by Django 5.1.7 on 2026-02-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0003_remove_customuser_section_customuser_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sec',
            new_name='section',
        ),
    ]
