# Generated by Django 5.1.7 on 2026-02-21 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0004_rename_event_title_event_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 12, 30, 15, 489901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 12, 30, 15, 489901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='position',
            field=models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICE-PRESIDENT', 'VICE-PRESIDENT'), ('CORE-MEMBER', 'CORE-MEMBER'), ('GENERAL-MEMBER', 'GENERAL-MEMBER'), ('COORDINATOR', 'COORDINATOR')], default='GENERAL-MEMBER', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubpayment',
            name='member_position',
            field=models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('VICE-PRESIDENT', 'VICE-PRESIDENT'), ('CORE-MEMBER', 'CORE-MEMBER'), ('GENERAL-MEMBER', 'GENERAL-MEMBER'), ('COORDINATOR', 'COORDINATOR')], default='GENERAL-MEMBER', max_length=100),
        ),
    ]
