# Generated by Django 5.1.7 on 2026-02-09 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0004_rename_sec_customuser_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='year',
            new_name='current_year',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_code_for_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registeration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'BSC'), ('MSC', 'MSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BALLAB', 'BALLAB'), ('LLB', 'LLB')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('B.TECH CSE', 'B.TECH CSE'), ('B.TECH CIVIL', 'B.TECH CIVIL'), ('B.TECH MECHANICAL', 'B.TECH MECHANICAL'), ('B.TECH ELECTRICAL', 'B.TECH ELECTRICAL'), ('M.TECH CSE', 'M.TECH CSE'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'BSC'), ('MSC', 'MSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BALLAB', 'BALLAB'), ('LLB', 'LLB')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, choices=[('B.TECH', 'B.TECH'), ('M.TECH', 'M.TECH'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'BSC'), ('MSC', 'MSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BALLAB', 'BALLAB'), ('LLB', 'LLB')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qid',
            field=models.CharField(default='000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('N_FACULTY', 'N_FACULTY'), ('DEAN', 'DEAN'), ('VC', 'VC')], default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('qid', models.CharField(blank=True, default='000000', max_length=15, null=True, unique=True)),
                ('face_encoding', models.BinaryField(blank=True, editable=True, null=True)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('N_FACULTY', 'N_FACULTY'), ('DEAN', 'DEAN'), ('VC', 'VC')], default=None, max_length=100)),
                ('country_code_for_mobile', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('registeration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_at', models.DateTimeField(default=None, null=True)),
                ('user_requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
