# Generated by Django 5.1.7 on 2026-02-21 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0005_remove_event_event_date_event_event_date_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpayment',
            name='member_position',
        ),
        migrations.AddField(
            model_name='clubpayment',
            name='is_paid_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubpayment',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 12, 33, 8, 825815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_from',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 12, 33, 8, 834388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 12, 33, 8, 834388, tzinfo=datetime.timezone.utc)),
        ),
    ]
