# Generated by Django 5.1.7 on 2025-11-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0005_rename_subjects_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ManyToManyField(to='Qapp.subject'),
        ),
    ]
