# Generated by Django 5.1.7 on 2026-02-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0005_rename_year_customuser_current_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='registeration_number',
            new_name='registration_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_code_for_mobile',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('N_FACULTY', 'N_FACULTY'), ('DEAN', 'DEAN'), ('VC', 'VC')], default='STUDENT', max_length=100),
        ),
    ]
