# Generated by Django 5.1.7 on 2025-11-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0006_section_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('president_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vise_president_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('president_mobile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('vise_president_mobile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('core_members', models.JSONField(blank=True, default={}, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('entry_fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
