# Generated by Django 5.1.7 on 2026-02-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0006_rename_registeration_number_pendinguser_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='registeration_number',
            new_name='registration_number',
        ),
    ]
