# Generated by Django 5.1.7 on 2026-02-21 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0006_remove_clubpayment_member_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpayment',
            name='payment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
