# Generated by Django 5.1.7 on 2026-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0008_customuser_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
