# Generated by Django 5.1.7 on 2026-02-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0009_alter_pendinguser_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='name',
            new_name='username',
        ),
    ]
