# Generated by Django 5.2.8 on 2025-11-16 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0009_club_student_enrolled_subject_faculty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubeventpayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
