# Generated by Django 5.1.7 on 2026-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0010_rename_name_pendinguser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='qid',
            new_name='QID_CUSTOMUSER',
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='qid',
            new_name='QID_PENDINGUSER',
        ),
    ]
