# Generated by Django 5.1.7 on 2026-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0010_clubeventpayment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
