# Generated by Django 5.2.8 on 2025-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0011_activetoken_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='activetoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
