# Generated by Django 5.1.7 on 2026-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0011_customuser_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_encoding',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
