# Generated by Django 5.1.7 on 2026-02-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0011_rename_qid_customuser_qid_customuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='QID_CUSTOMUSER',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='QID_PENDINGUSER',
            new_name='qid',
        ),
    ]
