# Generated by Django 5.1.7 on 2026-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0012_rename_qid_customuser_customuser_qid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('FACULTY', 'FACULTY'), ('VC', 'VC'), ('DEAN', 'DEAN'), ('DIRECTOR', 'DIRECTOR'), ('NON-FACULTY', 'NON-FACULTY'), ('ADMIN', 'ADMIN')], default='STUDENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('FACULTY', 'FACULTY'), ('VC', 'VC'), ('DEAN', 'DEAN'), ('DIRECTOR', 'DIRECTOR'), ('NON-FACULTY', 'NON-FACULTY'), ('ADMIN', 'ADMIN')], default=None, max_length=100),
        ),
    ]
