# Generated by Django 5.2.8 on 2025-12-01 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0012_remove_activetoken_created_at_activetoken_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AddField(
            model_name='activetoken',
            name='event_or_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.club'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event_or_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.club'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='mark_attendance_by_cordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='token_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.activetoken'),
        ),
        migrations.AlterField(
            model_name='activetoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.RemoveField(
            model_name='club',
            name='core_members',
        ),
        migrations.AddField(
            model_name='club',
            name='core_members',
            field=models.ManyToManyField(blank=True, related_name='core_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
