# Generated by Django 5.2.8 on 2025-12-06 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0013_rename_timestamp_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubEventPayment',
            new_name='ClubPayment',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='attendance_marked_at',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='mark_attendance_by_cordinator',
            new_name='attendance_marked_by_cordinator',
        ),
        migrations.RenameField(
            model_name='clubpayment',
            old_name='event_or_club',
            new_name='club',
        ),
        migrations.RemoveField(
            model_name='activetoken',
            name='event_or_club',
        ),
        migrations.RemoveField(
            model_name='activetoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='event_or_club',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='token_obj',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_mobile_number',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president_name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='student_enrolled',
        ),
        migrations.RemoveField(
            model_name='club',
            name='vise_president_mobile_number',
        ),
        migrations.RemoveField(
            model_name='club',
            name='vise_president_name',
        ),
        migrations.AddField(
            model_name='activetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activetoken',
            name='current_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='blocked_student',
            field=models.ManyToManyField(blank=True, related_name='blocked_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='club_video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/'),
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='club',
            name='members_detail',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_fees', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_free', models.BooleanField(default=False)),
                ('event_video', models.FileField(blank=True, null=True, upload_to='event_videos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('blocked_student', models.ManyToManyField(blank=True, related_name='blocked_students_from_event', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.club')),
            ],
        ),
        migrations.AddField(
            model_name='activetoken',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event'),
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qapp.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
