# Generated by Django 5.1.7 on 2026-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0013_alter_customuser_face_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
