# Generated by Django 5.1.7 on 2026-02-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0014_alter_pendinguser_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
