# Generated by Django 5.2.8 on 2025-12-12 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0014_rename_clubeventpayment_clubpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='student_enrolled',
            field=models.ManyToManyField(blank=True, related_name='student_enrolled_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='blocked_student',
            field=models.ManyToManyField(blank=True, related_name='blocked_students_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='core_members',
            field=models.ManyToManyField(blank=True, related_name='core_members_club', to=settings.AUTH_USER_MODEL),
        ),
    ]
