# Generated by Django 5.2.8 on 2025-12-12 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0015_club_student_enrolled_alter_club_blocked_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student_enrolled',
            field=models.ManyToManyField(blank=True, related_name='student_enrolled_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='blocked_student',
            field=models.ManyToManyField(blank=True, related_name='blocked_students_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
