# Generated by Django 5.2.8 on 2025-12-12 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0016_event_student_enrolled_alter_event_blocked_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_coordinator',
            field=models.ManyToManyField(blank=True, related_name='event_coordinator_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='faculty_assigned',
            field=models.ManyToManyField(blank=True, related_name='faculty_assigned_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
