# Generated by Django 5.2.8 on 2025-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0017_event_event_coordinator_event_faculty_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
