# Generated by Django 5.2.8 on 2025-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0019_certificate_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
