# Generated by Django 5.2.8 on 2025-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapp', '0020_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
